{
 "title": "Books-dasboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Volum Total Carti",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(book_count) AS value FROM language_stats;"
    }
   ]
  },
  {
   "title": "Rating Mediu Global",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(avg_rating * book_count) / SUM(book_count) AS value \r\nFROM language_stats;"
    }
   ]
  },
  {
   "title": "Evoluția Calității în Flux (Live Trend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  window_start AS time, \r\n  SUM(avg_rating * book_count) / SUM(book_count) AS value, \r\n  'Rating Mediu Real' AS metric\r\nFROM language_stats\r\nWHERE window_start > NOW() - INTERVAL '2 hours'\r\nGROUP BY window_start\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Numarul de carti pe limbi",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN language_code IN ('eng', 'en-US', 'en-GB', 'en-CA') THEN 'eng'\r\n    ELSE language_code \r\n  END AS metric,\r\n  SUM(book_count) AS value\r\nFROM language_stats\r\nGROUP BY \r\n  CASE \r\n    WHEN language_code IN ('eng', 'en-US', 'en-GB', 'en-CA') THEN 'eng'\r\n    ELSE language_code \r\n  END\r\nHAVING SUM(book_count) > 100\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Ratings pe edituri",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  publisher AS \"Editură\",\r\n  SUM(total_reviews) AS \"Impact (Reviews)\",\r\n  ROUND(AVG(avg_pages)::numeric, 1) AS \"Media Paginilor\",\r\n  MAX(window_start) AS \"Live Update\"\r\nFROM publisher_metrics\r\nWHERE window_start > NOW() - INTERVAL '30 minutes'\r\nGROUP BY publisher  \r\nORDER BY \"Impact (Reviews)\" DESC\r\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Top 10 autori cititi",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  author as metric,\r\n  SUM(reads_count) as value\r\nFROM top_authors\r\nWHERE window_start > NOW() - INTERVAL '15 minutes'\r\nGROUP BY author\r\nORDER BY value DESC\r\nLIMIT 10;\r\n\r\n"
    }
   ]
  }
 ]
}